[platformio]
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
;upload_protocol = espota
;upload_port = beau-trellis.local
build_flags = 
	-D DEVICE_NAME=\"Beau-Trellis\"
	-D CORE_DEBUG_LEVEL=3
lib_deps = 
	adafruit/Adafruit seesaw Library@^1.7.9
  
[env:seeed_xiao_esp32c3]
board = seeed_xiao_esp32c3

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3